### ISSUE TITLE
[BUMP] awsvpnclient 4.1.0 (supports openssl 3)

### ISSUE THREAD

**Issue by jorlando-elucid** [BOPOHA/aws-rpm-packages#32]
awsvpnclient is now on version 4.1.0. This seems to now use an embedded version of openssl 3, which will prevent us from having to manually install ssl 1 on Fedora 40+ versions.

**Comment by krg-digital** [comment]
Would much appreciate if we can get a 4.1.0 build! The OpenSSL1.1 dependency is a pain.

**Comment by BOPOHA** [comment]
> The OpenSSL1.1 dependency is a pain

done...  https://copr.fedorainfracloud.org/coprs/vorona/aws-rpm-packages/build/8269591/

will release update soon

**Comment by BOPOHA** [comment]
please check version 4.1.0

**Comment by mdschmitt** [comment]
4.1.0 broke my VPN on Fedora 40.  I now get "Connection Failed. Try again" when trying to connect.
Looking into why, here's part of the log (partially redacted):
```
2024-11-18 18:29:34.511 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:34 [example.clientvpn.com] Peer Connection Initiated with [AF_INET]X.X.X.X:443
2024-11-18 18:29:34.511 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:34 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
2024-11-18 18:29:34.511 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:34 TLS: tls_multi_process: initial untrusted session promoted to trusted
2024-11-18 18:29:35.190 +09:00 [DBG] [TI=7] /bin/ps exit code: 0
2024-11-18 18:29:35.599 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 MANAGEMENT: >STATE:1731922175,GET_CONFIG,,,,,,
2024-11-18 18:29:35.599 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 SENT CONTROL [example.clientvpn.com]: 'PUSH_REQUEST' (status=1)
2024-11-18 18:29:35.600 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.16.0.2,route 10.16.0.0 255.255.255.0,route 10.0.0.0 255.0.0.0,route 172.16.0.0 255.240.0.0,route-gateway 192.168.X.X,topology subnet,ping 1,ping-restart 20,echo,echo,echo,ifconfig 192.168.X.X 255.255.255.224,peer-id 0,cipher AES-256-GCM,protocol-flags cc-exit tls-ekm dyn-tls-crypt,tun-mtu 1500'
2024-11-18 18:29:35.600 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 OPTIONS IMPORT: --ifconfig/up options modified
2024-11-18 18:29:35.600 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 OPTIONS IMPORT: route options modified
2024-11-18 18:29:35.600 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 OPTIONS IMPORT: route-related options modified
2024-11-18 18:29:35.601 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2024-11-18 18:29:35.601 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 OPTIONS IMPORT: tun-mtu set to 1500
2024-11-18 18:29:35.601 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 ROUTE_GATEWAY 10.226.1.129/255.255.255.128 IFACE=enp0s13f0u1u1 HWADDR=XX:XX:XX:XX:XX:XX
2024-11-18 18:29:35.604 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 TUN/TAP device tun0 opened
2024-11-18 18:29:35.604 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 MANAGEMENT: >STATE:1731922175,ASSIGN_IP,,192.168.10.162,,,,
2024-11-18 18:29:35.604 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 /sbin/ip link set dev tun0 up mtu 1500
2024-11-18 18:29:35.607 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 /sbin/ip link set dev tun0 up
2024-11-18 18:29:35.611 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 /sbin/ip addr add dev tun0 192.168.10.162/27
2024-11-18 18:29:35.614 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 /opt/awsvpnclient/Resources/openvpn/configure-dns tun0 1500 0 192.168.X.X 255.255.255.224 init
2024-11-18 18:29:35.640 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 MANAGEMENT: Client disconnected
2024-11-18 18:29:35.640 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 WARNING: Failed running command (--up/--down): could not execute external program
2024-11-18 18:29:35.640 +09:00 [DBG] [TI=12] [PID: 556667] 2024-11-18 18:29:35 Exiting due to fatal error
2024-11-18 18:29:35.656 +09:00 [DBG] [TI=7] /bin/ps exit code: 0
2024-11-18 18:29:36.669 +09:00 [DBG] [TI=11] /bin/ps exit code: 1
2024-11-18 18:29:36.669 +09:00 [ERR] [TI=11] Failed to get process owner of PID: 556667. Stdout: , stderr: 
2024-11-18 18:29:36.674 +09:00 [WRN] [TI=11] Exception occured checking process alive: System.Exception: Failed to get process owner of PID: 556667
   at ACVC.GTK.Service.DBus.OvpnGtkService.GetProcessOwner(Int32 pid)
   at ACVC.GTK.Service.DBus.OvpnGtkService.IsAliveAsync(Int32 pid)
2024-11-18 18:29:36.677 +09:00 [DBG] [TI=11] Wait for OpenVPN processes to finish graceful shutdown
2024-11-18 18:29:36.686 +09:00 [DBG] [TI=11] All OpenVPN processes exited properly
2024-11-18 18:29:36.686 +09:00 [DBG] [TI=11] Finished waiting OpenVPN graceful shutdown. Proceed with killing any orphaned OpenVPN processes
2024-11-18 18:29:36.794 +09:00 [DBG] [TI=11] Orphaned process are alive: False
2024-11-18 18:29:36.795 +09:00 [DBG] [TI=11] Attempting to restore /etc/resolv.conf if /etc/resolv.conf.ovpnsave exists
2024-11-18 18:29:36.795 +09:00 [DBG] [TI=11] /etc/resolv.conf.ovpnsave not found
2024-11-18 18:29:36.796 +09:00 [DBG] [TI=11] Deleting connection info files on disconnect
2024-11-18 18:29:36.798 +09:00 [DBG] [TI=11] Number of stale connection info files: 0
2024-11-18 18:29:36.798 +09:00 [DBG] [TI=11] Deleted all stale connection info files in /opt/awsvpnclient/ConnectionInfoFiles.
```

**Comment by mdschmitt** [comment]
I'm almost certain the problem lies with the `configure-dns` script but when I try to add some lines or change it to debug, things immediately fail.
```
Mon Nov 18 21:08:23 JST 2024 Executing up script with parameters 'tun0 1500 0 192.168.x.x 255.255.255.224 init'
Mon Nov 18 21:08:23 JST 2024 Configuring to use DNS servers from OpenVPN
Mon Nov 18 21:08:23 JST 2024 Getting DNS servers from OpenVPN
Mon Nov 18 21:08:23 JST 2024 foreign_option_1 from OpenVPN: dhcp-option DOMAIN xx.xx
Mon Nov 18 21:08:23 JST 2024 foreign_option_2 from OpenVPN: dhcp-option DOMAIN xx.xxy
Mon Nov 18 21:08:23 JST 2024 foreign_option_3 from OpenVPN: dhcp-option DOMAIN xx.xxz
Mon Nov 18 21:08:23 JST 2024 foreign_option_5 from OpenVPN: dhcp-option DNS 10.16.0.2
Mon Nov 18 21:08:23 JST 2024 Getting device index for tun0
Mon Nov 18 21:08:23 JST 2024 'ip link show dev tun0' exit code: 127, output: 
```

**Comment by pulsar895** [comment]
Same problem as @mdschmitt on my Fedora 41

**Comment by mdschmitt** [comment]
🤦🏼  Pretty sure I found it.  It's a regression.  

The original issue: https://github.com/BOPOHA/aws-rpm-packages/issues/4 
The current status: that PATH patch didn't make it into the 4.1.0 RPM somehow.

**Comment by pulsar895** [comment]
On my workstation, I see the patch in `Service/Resources/openvpn/configure-dns`, so I think this is not the problem.
Please, someone can share to me the previous rpm package ? My dnf cache is empty, so I can't downgrade...

**Comment by mdschmitt** [comment]
Maybe I spoke too soon, I hope @BOPOHA can shed some light.  I built the 3.14 RPM from this repo, but GitHub won't let me attach it for obvious reasons.  Where do you want it?

**Comment by pulsar895** [comment]
I hope so too!
Can you send it to https://ch.skysend.ch please?

**Comment by mdschmitt** [comment]
well, I guess it's better if you DIY it.  This is what I did (reused an old docker builder for other RPMs, so kinda shotgunned the dependencies, you can slim it down if you like, but this will get you back online):

```Dockerfile
FROM fedora:40 AS builder

# Update dnf, see note below!
RUN dnf update -y && dnf clean all

# Install build dependencies for your project(s)
# fedpkg fedora-packager
RUN dnf install -y rpmdevtools ncurses-devel pesign bpftool bc bison dwarves elfutils-devel \
    flex gcc gcc-c++ gcc-plugin-devel git-all glibc-static hostname m4 make net-tools \
    openssl openssl-devel perl-devel perl-generators python3-devel which kernel-rpm-macros \
    asciidoc zsh \
    && dnf clean all

# Setup build directory
# RUN rpmdev-setuptree
RUN mkdir -p ~/rpmbuild
```

1. docker build . -t fedora40packagebuilder:latest
2. clone this repo, cd into it and checkout d240cadd9ac74ac25b8b592fa57d1279f75cd39a
3. cd to `awsvpnclient`
4. `mkdir {BUILD,BUILDROOT,SOURCES,SPECS,SRPMS,RPMS}`
5. `mv *.spec SPECS/`
6. `mv * SOURCES`
7. `docker run -it -v "$(pwd):/root/rpmbuild" fedora40packagebuilder:latest /bin/bash`
and inside the container:
1. `spectool -g -R /root/rpmbuild/awsvpnclient/SOURCES/awsvpnclient.spec`
2. `rpmbuild -bb /root/rpmbuild/awsvpnclient/SPECS/awsvpnclient.spec`

and then just `sudo dnf install` the resulting RPM from the RPMS directory in your repo dir.

**Comment by mdschmitt** [comment]
but here's the link for lazy folks: https://ch.skysend.ch/download/797f7bf4f06c6476/#mDxz2QTm2ine1xGiOtPxQw

**Comment by pulsar895** [comment]
Thank you, that fix the problem!

**Comment by BOPOHA** [comment]
ok, i'm here
[Houston, we have a problem](https://en.wikipedia.org/wiki/Houston,_we_have_a_problem)

1. i do not use DNS feature, i can not check the `configure-dns`
2. i disabled the patch for `configure-dns`... because... they have hash validation for at least `configure-dns` and `acvc-openvpn`. will need to find another way...
3. 3.14 re-uploaded https://copr.fedorainfracloud.org/coprs/vorona/aws-rpm-packages/build/8278216/

**Comment by BOPOHA** [comment]
```
$ which systemd-resolve busctl   ip
/usr/bin/systemd-resolve
/usr/bin/busctl
/usr/sbin/ip
```

```
$ env -i bash -c 'echo $PATH'
/usr/local/bin:/usr/bin
```


so. dirty option is to create symlink... let's skip it for now

2nd option is to update the systemd
3rd option - to play with /etc/ config files
4th - build/wrap own custom /usr/local/bin/bash
5... ld preload way... is also dirty from RPM spec repspective

----

to check the 2nd option
**please,** 
create the file `/etc/systemd/system/awsvpnclient.service.d/override.conf` with next content

```
[Service]
Environment="PATH=/usr/sbin:/usr/bin:/usr/local/bin"

```

then run `systemctl daemon-reload` and  `systemctl restart daemon-reload`

---

**Comment by mdschmitt** [comment]
`ln -s /usr/sbin/ip /usr/bin/ip` , not the other way 'round, but I just tried that and it works!!!

**Comment by mdschmitt** [comment]
man, that hash validation thing is super annoying
